#pragma once
#include <3ds.h>

#define RES_APT_CANCELED             MAKERESULT(RL_STATUS, RS_STATUSCHANGED, RM_APPLICATION, RD_CANCEL_REQUESTED)
#define RES_USER_CANCELED            MAKERESULT(RL_STATUS, RS_CANCELED, RM_APPLICATION, RD_CANCEL_REQUESTED)
#define RES_FAILED_PARSE             MAKERESULT(RL_FATAL, RS_CANCELED, RM_APPLICATION, RD_NO_DATA)

#define RES_SRV_NO_SERVICE_PERMS     MAKERESULT(RL_PERMANENT, RS_INVALIDARG, RM_SRV, 6)
#define RES_OS_REMOTE_SESSION_CLOSED MAKERESULT(RL_STATUS, RS_CANCELED, RM_OS, 26)

#define RES_DATA_TOO_LARGE           MAKERESULT(RL_STATUS, RS_OUTOFRESOURCE, RM_APPLICATION, RD_TOO_LARGE)
#define RES_OUT_OF_BOUNDS            MAKERESULT(RL_STATUS, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_RANGE)
#define RES_NO_MEMORY                MAKERESULT(RL_STATUS, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
#define RES_ROP_TOO_LARGE            MAKERESULT(RL_STATUS, RS_INTERNAL, RM_APPLICATION, RD_TOO_LARGE)
#define RES_INVALID_SIZE             MAKERESULT(RL_STATUS, RS_INTERNAL, RM_APPLICATION, RD_INVALID_SIZE)
#define RES_INVALID_HANDLE           MAKERESULT(RL_STATUS, RS_INTERNAL, RM_APPLICATION, RD_INVALID_HANDLE)
#define RES_NOT_FOUND                MAKERESULT(RL_STATUS, RS_NOTFOUND, RM_APPLICATION, RD_NOT_FOUND)
#define RES_NO_DATA                  MAKERESULT(RL_STATUS, RS_NOTFOUND, RM_APPLICATION, RD_NO_DATA)
#define RES_INVALID_VALUE            MAKERESULT(RL_STATUS, RS_INVALIDSTATE, RM_APPLICATION, RD_NO_DATA)
